apiVersion: v1
kind: PersistentVolume
metadata:
  name: external-data-pv
  finalizers: []
  labels:
    hostNetwork: "false"
    internal-service: "false"
    managed-by: chynten
    created-by: chynten
    version: "1.0.0"
spec:
  volumeMode: Filesystem
  capacity:
    storage: 128Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-class
  local:
    path: /opt/data/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - your-pc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: external-media-pv
  finalizers: []
  labels:
    hostNetwork: "false"
    internal-service: "false"
    managed-by: chynten
    created-by: chynten
    version: "1.0.0"
spec:
  capacity:
    storage: 2.5Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-class
  local:
    path: /mnt/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - your-pc