apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: external-data-pvc
  namespace: external
  finalizers: []
  labels:
    hostNetwork: "false"
    internal-service: "false"
    managed-by: chynten
    created-by: chynten
    version: "1.0.0"
spec:
  accessModes:
    - ReadWriteMany
  volumeName: external-data-pv
  storageClassName: local-storage-class
  resources:
    requests:
      storage: "128Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: external-media-pvc
  namespace: external
  finalizers: []
  labels:
    hostNetwork: "false"
    internal-service: "false"
    managed-by: chynten
    created-by: chynten
    version: "1.0.0"
spec:
  accessModes:
    - ReadWriteMany
  volumeName: external-media-pv
  storageClassName: local-storage-class
  resources:
    requests:
      storage: "2.5Ti"