apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: internal-sites
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: external-sites
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
