apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard
  namespace: argocd
spec:
  destination:
    namespace: internal
    server: https://kubernetes.default.svc
  project: internal-sites
  source:
    chart: adguard
    helm:
      parameters:
        - name: image.repository
          value: "adguard/adguardhome"
        - name: image.tag
          value: "v0.107.0-b.13"
        - name: ingress.hosts[0].host
          value: dns.internal.example.com
        - name: ingress.tls[0].hosts[0]
          value: dns.internal.example.com
        - name: storage.conf.subPath
          value: adguard/conf
        - name: storage.data.subPath
          value: adguard/data
#        - name: resources.requests.cpu
#          value: 40m
#        - name: resources.limits.cpu
#          value: 60m
#        - name: resources.requests.memory
#          value: 80Mi
#        - name: resources.limits.memory
#          value: 120Mi
      valueFiles:
        - values.yaml
    repoURL: https://homeenterpriseinc.github.io/helm-charts/
    targetRevision: "0.1"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
