apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homebridge
  namespace: argocd
spec:
  destination:
    namespace: internal
    server: https://kubernetes.default.svc
  project: internal-sites
  source:
    chart: homebridge
    helm:
      parameters:
        - name: image.repository
          value: "oznu/homebridge"
        - name: image.tag
          value: "ubuntu"
        - name: image.pullPolicy
          value: Always
        - name: probe.enable
          value: "false"
        - name: ingress.hosts[0].host
          value: homebridge.internal.example.com
        - name: ingress.tls[0].hosts[0]
          value: homebridge.internal.example.com
#        - name: resources.requests.cpu
#          value: 50m
#        - name: resources.limits.cpu
#          value: 70m
#        - name: resources.requests.memory
#          value: 120Mi
#        - name: resources.limits.memory
#          value: 180Mi
      valueFiles:
        - values.yaml
    repoURL: https://homeenterpriseinc.github.io/helm-charts/
    targetRevision: "0.1"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
