apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  destination:
    namespace: external
    server: https://kubernetes.default.svc
  project: external-sites
  source:
    chart: keycloak
    helm:
      parameters:
        - name: image.repository
          value: "jboss/keycloak"
        - name: image.tag
          value: "15.0.2"
        - name: ingress.hosts[0].host
          value: keycloak.example.com
        - name: ingress.tls[0].hosts[0]
          value: keycloak.example.com
        - name: probe.enable
          value: "false"
        - name: keycloak.javaOpts
          value: "-server -Xms350m -Xmx750m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true   --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED"
#        - name: resources.requests.cpu
#          value: 100m
#        - name: resources.limits.cpu
#          value: 250m
#        - name: resources.requests.memory
#          value: 350Mi
#        - name: resources.limits.memory
#          value: 750Mi
      valueFiles:
        - values.yaml
    repoURL: https://homeenterpriseinc.github.io/helm-charts/
    targetRevision: "0.1"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true