apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-certificate
  namespace: argocd
spec:
  dnsNames:
    - argocd.internal.example.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: argocd-letsencrypt-certificate